name = "tomsimko-contact"
main = "workers/contact.ts"
compatibility_date = "2026-08-01"
workers_dev = false

[[routes]]
pattern = "api.tomsimko.com"
custom_domain = true

[[ratelimits]]
name = "CONTACT_RATE_LIMITER"
namespace_id = "87010401"

  [ratelimits.simple]
  limit = 5
  period = 60
